#!/usr/bin/env bash
set -ex

INPUT_DIR="static"
DIST_DIR="dist"
OUTPUT_DIR="demo"

preflight() {

  if [ ! -d $DIST_DIR ]; then
    echo "YOu need to execute the `${DIST_DIR}` command prior to create the demo files"
    exit 0
  fi

  echo "Preparing for takeoff";
  if [ ! -d $OUTPUT_DIR ]; then
    mkdir -p $OUTPUT_DIR
  fi
}


building() {

  echo "Building demo";
  cp -R $INPUT_DIR/* $OUTPUT_DIR
  cp -R $DIST_DIR/* $OUTPUT_DIR
  if [ -d $OUTPUT_DIR ]; then
    rm -rf $OUTPUT_DIR/bootstrap
  fi

}

preflight;
building;