#!/usr/bin/env bash
set -ex

TARGET_FILES=( "nocc-theme.css" "jq-bootstrap-validation.js" "theme-toggler.js" );
INPUT_DIR="src";
OUTPUT_DIR="dist/src";
THEME="nocc-bootstrap-theme";


preflight() {

  rm -rf dist && mkdir -p dist
	if [ ! -d $INPUT_DIR ]; then
    echo "Directory `src` not found";
    exit 0;
	fi

}


compiling() {

  npm run compile

}


building() {

	for file in "${TARGET_FILES[@]}"; do
    name="${file%.*}"
    ext="${file##*.}"
    if [ $ext == "css" ]; then
  		TYPE="text/css"
    fi
    if [ $ext == "js" ]; then
  		TYPE="text/javascript"
    fi
    #minimizing;
	done

}


minimizing() {

  minify --type=${TYPE} < ${OUTPUT_DIR}/${ext}/${file} > ${OUTPUT_DIR}/${ext}/${name}.min.${ext}

}


preflight;
compiling;
building;