#!/usr/bin/env bash
set -ex

INPUT_DIR="src";
OUTPUT_DIR="dist";
THEME="nocc-bootstrap-theme";


preflight() {

  rm -rf dist && mkdir -p dist
	if [ ! -d $INPUT_DIR ]; then
    echo "Directory `src` not found";
    exit 0;
	fi

}


compiling() {

  npm run compile

}


preflight;
compiling;