name: npm-publish-test
on: ["push", "pull_request"]
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - name: Build
        run: |
          npm run dist
          ls -lah dist/
      - name: minisauras
        uses: TeamTigers/minisauras@v2.0.0
        with:
          directory: 'dist/'
        id: dir
        env:
          GITHUB_TOKEN: ${{ secrets.NOCC_ACTIONS_TOKEN }}