# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: nocc-bootstrap-theme

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - name: Publish the release to NPM
        run: npm publish --provenance --access public
        working-directory: ./dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMPUBTOKEN}}
