name: npm-publish-test
on: ["push", "pull_request"]
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    environment:
      name: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.10'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - name: Build
        run: |
          npm run dist
          du -a dist/
      - name: CSS Minifier
        uses: devatherock/minify-js@v3.0.0
        with:
          directory: 'dist/css'
      - name: JS Minifier
        uses: devatherock/minify-js@v3.0.0
        with:
          directory: 'dist/js'
      - run: du -a dist/
      - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
      - run: cd dist/ && npm pack
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: package
            path: "*.tgz"