name: npm-publish-test
on: ["push", "pull_request"]
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    environment:
      name: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.10'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci

      - name: Build
        run: |
          npm run dist
          du -a dist/

      - name: minisauras CSS
        uses: TeamTigers/minisauras@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.NOCC_ACTIONS_TOKEN }}
        id: dir
        with:
          directory: 'dist/css/'
      - run: du -a dist/