name: test-sass
on: 
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
    - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
      - name: Run lint
        run: npm run lint
      - name: Build distribution
        run: npm ci
